[workspace]
resolver = "3"
members = [
  "engine",
  "kvs/api",
  "kvs/rest/client",
  "kvs/rest/common",
  "kvs/rest/server",
  "kvs/rest/tests",
  "kvs/tck",
]

[workspace.dependencies]
# Internal
engine = { package = "animus-engine", path = "engine" }
kvs-api = { package = "animus-kvs-api", path = "kvs/api" }
kvs-rest-client = { package = "animus-kvs-rest-client", path = "kvs/rest/client" }
kvs-rest-common = { package = "animus-kvs-rest-common", path = "kvs/rest/common" }
kvs-rest-server = { package = "animus-kvs-rest-server", path = "kvs/rest/server" }
kvs-tck = { package = "animus-kvs-tck", path = "kvs/tck" }

# External
async-stream = "0.3.6"
axum = "0.8.9"
axum-extra = "0.12.6"
base64 = "0.23.0"
bytes = "1.12.1"
console-subscriber = "0.5.0"
csv = "1.4.0"
csv-async = "1.3.1"
futures = "0.3.32"
futures-core = "0.3.33"
headers = "0.4.1"
headers-accept = "0.3.0"
http = "1.4.2"
httpmock = "0.8.3"
mediatype = "0.21.0"
mockall = "0.15.0"
reqwest = "0.13.4"
serde = "1.0.228"
thiserror = "2.0.18"
tokio = "1.52.3"
tokio-util = "0.7.18"
tower = "0.5.3"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tracing-test = "0.2.6"
validator = "0.21.0"
