[package]
name = "animus-kvs-rest-server"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
engine.workspace = true
kvs-api.workspace = true
kvs-rest-common.workspace = true

# External
async-stream.workspace = true
axum = { workspace = true, features = ["macros"] }
axum-extra = { workspace = true, features = ["typed-header"] }
base64.workspace = true
bytes.workspace = true
csv-async.workspace = true
futures.workspace = true
headers.workspace = true
headers-accept.workspace = true
mediatype.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-test.workspace = true
validator.workspace = true

[dev-dependencies]
engine.workspace = true
futures.workspace = true
tower.workspace = true
